export const favoriteTypes = [
  { id: "travel", label: "Favorite Travel destination", icon: "✈️" },
  { id: "restaurant", label: "Favorite Restaurant", icon: "🍽️" },
  { id: "food", label: "Favorite Food/Dish", icon: "🍳" },
  { id: "drink", label: "Favorite Drink", icon: "🥤" },
  { id: "color", label: "Favorite Color", icon: "🎨" },
  { id: "music", label: "Favorite Music", icon: "🎵" },
  { id: "tv", label: "Favorite TV Show", icon: "📺" },
  { id: "movie", label: "Favorite Movie", icon: "🎬" },
  { id: "book", label: "Favorite Book", icon: "📚" },
  { id: "game", label: "Favorite Game to Play", icon: "🎮" },
  { id: "exercise", label: "Favorite Exercise", icon: "🏃" },
  { id: "sport", label: "Favorite Sport", icon: "⚽" },
  { id: "team", label: "Favorite Sports Team", icon: "👥" },
  { id: "local", label: "Favorite Local Sport", icon: "🏆" },
  { id: "quote", label: "Favorite Quote/Saying", icon: "💭" },
  { id: "cause", label: "Important Cause", icon: "❤️" },
  { id: "fact", label: "Fun Fact", icon: "💡" },
  { id: "custom", label: "Custom Question", icon: "❓" },
];
