export { default as IconSearch } from "./IconSearch";
export { default as IconBook } from "./IconBook";
export { default as IconQR } from "./IconQR";
export { default as IconClock } from "./IconClock";
export { default as IconWeb } from "./IconWeb";
export { default as IconEmail } from "./IconEMail";
export { default as IconShop } from "./IconShop";
export { default as IconFuneral } from "./IconFuneral";
export { default as IconSetting } from "./IconSetting";
